### PR TITLE
Add table of contents.

### PR DESCRIPTION
**Pull request by lberki**
Only tested on a Chromebook and Firefox on Android.

### CODE REVIEW

**Comment by EmielH** [comment]
Thanks for your contribution! It's a large one 😄 I had a quick look this weekend, will try to merge soon!

**Comment by lberki** [comment]
(friendly ping)

**Comment by EmielH** [comment]
Thanks for the ping. My apologies - I've had a busy couple of weeks!

**Comment by lberki** [comment]
Thanks! I can relate to the busy couple of weeks part :)

TBH I was expecting a long and meticulous code review given my experience in frontend development (or lack thereof), but if I managed to clear the quality bar on the first go, all the better.

**Pull request merged**
