### PR TITLE
Blog title is h1 on homepage

### LINKED ISSUE #52: Multiple `<h1>` tags on home page
By default, each post has an `<h1>` tag on the homepage listing of blog posts. This is incorrect from an SEO perspective. There should only ever be one `<h1>` tag on a page.

On the home page, the blog title should be the `<h1>` and the blog post list should have `<h2>`.

image
https://chesterhow.github.io/tale/

### PR DESCRIPTION
**Pull request by gavinr**
partially resolves #52

### CODE REVIEW

**Comment by EmielH** [comment]
Thank you very much for your contribution! This is a good catch. I wonder if on the article page, the title of the blog shouldn't be an `<h1>` too while the title of the article becomes an `<h2>`. This would probably fit the hierarchy better, while the title of the article can still be larger thanks to styling.

**Comment by gavinr** [comment]
It's best-practice on the article page to have the post title be the only H1 on the page. See the example of the official WordPress Twenty-One theme, for example:  https://wp-themes.com/twentytwentyone/?p=19

image

**Comment by EmielH** [comment]
That makes sense too. There's something to say for both approaches I guess! I can even consider removing the header tag from the site title altogether.

For now, I will accept your pull requests. Thanks again for your contribution!

**Comment by gavinr** [comment]
You're welcome. Thank you for maintaining this project!

**Pull request merged**
