### PR TITLE
translation to Spanish

### PR DESCRIPTION
**Pull request by vilarfg**

### CODE REVIEW

**Comment by EmielH** [comment]
Thanks a lot for this translation! It looks to me like the months are abbreviations of the month names, is that something that's commonly used in Spanish? The Dutch months have their full names translated, that's something I would like to keep consistent, but of course I don't know what's common in other countries. :)

**Comment by vilarfg** [comment]
I agree: consistency is important. In this scenario is a little tricky though, let me explain:

- 28-feb-2018: OK
- **28 de febrero de 2018**: also OK (nicest option but longer though, I suggest you pick this one and made a new commit with full names for months)
- 28-febrero-2018: understandable, but not really the way we display dates in Spanish.

**Comment by EmielH** [comment]
Awesome, sounds good to me! Could you change the translation of `publishdate` in `es.toml` to reflect "28 de febrero de 2018"? Then I'll merge this pull request.

**Comment by EmielH** [comment]
Thanks a lot, looks good to me! I'll merge this into master

**Pull request merged**
